on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./themes/our-awesome-theme
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
 
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:  
        ftp-server: 108.167.188.70
        ftp-username: batat328
        ftp-password: ${{ secrets.BATATA_FTP_PASS }}
        local-dir: ./our-awesome-theme/
