name: Staging Deploy

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
      
    - name: Install Composer Dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Install NPM packages
      run: npm install

    - name: Generate bundled theme with all assets
      run: npm run bundle
      
    - name: FTP Deploy to WP Engine (Staging)
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: 108.167.188.70
        ftp-username: batat328
        ftp-password: ${{ secrets.BATATA_FTP_PASS }}
